Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/conda/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/conda/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/conda/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/opt/conda/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/conda/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/conda/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp

g = 9.8 #m/s^2
r = 0.1 #1/s

def diffeq(x, y):
  z, vx, vz = y
  return [vz/vx,
          -r,
          (-r*vz-g)/vx]


def BVP_satisfy(x):
  v, theta_deg = x
  theta_rad = theta_deg/360*2*np.pi
  y0 = [100,v*np.cos(theta_rad), v*np.sin(theta_rad)]
  
  sol = solve_ivp(diffeq,
                [0,200],
                y0,
                t_eval=np.linspace(0,200))

  print(f'{v:1.17f}, {theta_deg:1.17f}')
  return [sol.y[0,-1],
          0]

fsolve_sol = fsolve(BVP_satisfy,[30,50])

print(fsolve_sol)

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn [4], line 29[0m
[1;32m     25[0m   [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m'[39m[38;5;132;01m{[39;00mv[38;5;132;01m:[39;00m[38;5;124m1.17f[39m[38;5;132;01m}[39;00m[38;5;124m, [39m[38;5;132;01m{[39;00mtheta_deg[38;5;132;01m:[39;00m[38;5;124m1.17f[39m[38;5;132;01m}[39;00m[38;5;124m'[39m)
[1;32m     26[0m   [38;5;28;01mreturn[39;00m [sol[38;5;241m.[39my[[38;5;241m0[39m,[38;5;241m-[39m[38;5;241m1[39m],
[1;32m     27[0m           [38;5;241m0[39m]
[0;32m---> 29[0m fsolve_sol [38;5;241m=[39m [43mfsolve[49m(BVP_satisfy,[[38;5;241m30[39m,[38;5;241m50[39m])
[1;32m     31[0m [38;5;28mprint[39m(fsolve_sol)

[0;31mNameError[0m: name 'fsolve' is not defined
NameError: name 'fsolve' is not defined

